"""
Django settings for lti project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(zj*=p0e++sk^2!xm5jko_p6j^0ohrvpet)c9*#!4d(im-i)xg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tool',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lti.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import os

# LTI settings
LTI_CLIENT_ID = "10000000000006"
LTI_DEPLOYMENT_ID = "10:f97330a96452fc363a34e0ef6d8d0d3e9e1007d2"

LTI_ISS = "https://canvas.instructure.com"  # Canvas uses this even in dev
# LTI_PLATFORM_JWKS_URL = "http://canvas.docker/api/lti/security/jwks"
# LTI_AUTHORIZE_URL = "http://canvas.docker/api/lti/authorize_redirect"

LTI_ISS = "https://canvas.instructure.com"  # Canvas uses this even in dev
LTI_PLATFORM_JWKS_URL = "https://canvas.ninepointeightone.com/api/lti/security/jwks"
LTI_AUTHORIZE_URL = "https://canvas.ninepointeightone.com/api/lti/authorize_redirect"

LTI_TOOL_REDIRECT_URI = "http://localhost:8000/launch/"

# Cookie settings so Firefox works in localhost (insecure ok for dev)
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False        # must be False for non-HTTPS
SESSION_COOKIE_DOMAIN = None  # critical for cross-site cookies

CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = False


CSRF_TRUSTED_ORIGINS = [
    "http://canvas.docker",
    "https://canvas.docker",
    "http://localhost:8000",
    "http://canvas.ninepointeightone.com"
    "https://canvas.ninepointeightone.com"
]

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_DOMAIN = "localhost"
X_FRAME_OPTIONS = "ALLOWALL"
