# Generated by Django 5.0 on 2025-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_toolconfig_interactionlog_vivasession_vivamessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolconfig',
            name='authorize_url',
            field=models.URLField(default='https://canvas.ninepointeightone.com/api/lti/authorize_redirect'),
            preserve_default=False,
        ),
    ]
