# Generated by Django 5.0 on 2025-11-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_toolconfig_authorize_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolconfig',
            name='redirect_url',
            field=models.URLField(default='https://app2.ninepointeightone.com/launch/'),
            preserve_default=False,
        ),
    ]
