# Generated by Django 5.0 on 2025-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_toolconfig_redirect_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolconfig',
            old_name='redirect_url',
            new_name='redirect_uri',
        ),
    ]
